// Shared symbol catalogue for prices/history APIs.
// Each entry maps a friendly ticker to a Yahoo Finance symbol.
//
// `priceCurrency` defaults to 'USD' for tradeable assets. `category`
// 'FX' entries describe a currency pair via {base, quote}; we use them
// to power the dashboard currency converter and the global ccy
// switcher in the nav.

const stk = (ticker, name, category, yahoo = ticker) =>
  ({ ticker, symbol: ticker, name, category, unit: '$', yahoo });
const fut = (ticker, symbol, name, category, unit, yahoo) =>
  ({ ticker, symbol, name, category, unit, yahoo });
const idx = (ticker, symbol, name, unit, yahoo) =>
  ({ ticker, symbol, name, category: 'MACRO', unit, yahoo });
const crypto = (ticker, name, yahoo = `${ticker}-USD`) =>
  ({ ticker, symbol: ticker, name, category: 'CRYPTO', unit: '$', yahoo });
const fx = (base, quote, name, yahoo = `${base}${quote}=X`) =>
  ({ ticker: `${base}${quote}`, symbol: `${base}/${quote}`, name, category: 'FX', unit: 'rate', yahoo, base, quote });

export const SYMBOLS = [
  // ENERGY
  fut('CL', 'WTI', 'WTI Crude', 'ENERGY', '$/bbl', 'CL=F'),
  fut('BZ', 'BRENT', 'Brent Crude', 'ENERGY', '$/bbl', 'BZ=F'),
  fut('NG', 'NATGAS', 'Natural Gas', 'ENERGY', '$/MMBtu', 'NG=F'),
  // METALS
  fut('GC', 'GOLD', 'Gold', 'METALS', '$/oz', 'GC=F'),
  fut('SI', 'SILVER', 'Silver', 'METALS', '$/oz', 'SI=F'),
  fut('HG', 'COPPER', 'Copper', 'METALS', '$/lb', 'HG=F'),
  // AGRI — note: SOY ticker (not 'ZS') to avoid collision with
  // Zscaler stock, which Yahoo also exposes under 'ZS'.
  fut('ZW', 'WHEAT', 'Wheat', 'AGRICULTURE', '¢/bu', 'ZW=F'),
  fut('ZC', 'CORN', 'Corn', 'AGRICULTURE', '¢/bu', 'ZC=F'),
  fut('SOY', 'SOY', 'Soybeans', 'AGRICULTURE', '¢/bu', 'ZS=F'),

  // TECH (mega-cap)
  stk('AAPL', 'Apple', 'TECH'),
  stk('MSFT', 'Microsoft', 'TECH'),
  stk('GOOGL', 'Alphabet', 'TECH'),
  stk('META', 'Meta Platforms', 'TECH'),
  stk('AMZN', 'Amazon', 'TECH'),
  stk('NFLX', 'Netflix', 'TECH'),
  stk('ADBE', 'Adobe', 'TECH'),
  stk('CRM', 'Salesforce', 'TECH'),
  stk('ORCL', 'Oracle', 'TECH'),
  stk('IBM', 'IBM', 'TECH'),
  stk('NOW', 'ServiceNow', 'TECH'),
  stk('INTU', 'Intuit', 'TECH'),

  // SEMI
  stk('NVDA', 'Nvidia', 'SEMI'),
  stk('AVGO', 'Broadcom', 'SEMI'),
  stk('AMD', 'AMD', 'SEMI'),
  stk('TSM', 'TSMC', 'SEMI'),
  stk('INTC', 'Intel', 'SEMI'),
  stk('MU', 'Micron', 'SEMI'),
  stk('QCOM', 'Qualcomm', 'SEMI'),
  stk('ASML', 'ASML', 'SEMI'),
  stk('AMAT', 'Applied Materials', 'SEMI'),
  stk('LRCX', 'Lam Research', 'SEMI'),
  stk('KLAC', 'KLA', 'SEMI'),
  stk('MRVL', 'Marvell', 'SEMI'),
  stk('TXN', 'Texas Instruments', 'SEMI'),
  stk('ADI', 'Analog Devices', 'SEMI'),
  stk('NXPI', 'NXP Semi', 'SEMI'),
  stk('MCHP', 'Microchip Tech', 'SEMI'),

  // DATA / AI / cyber / cloud
  stk('PLTR', 'Palantir', 'DATA'),
  stk('SNOW', 'Snowflake', 'DATA'),
  stk('NET', 'Cloudflare', 'DATA'),
  stk('DDOG', 'Datadog', 'DATA'),
  stk('MDB', 'MongoDB', 'DATA'),
  stk('CRWD', 'CrowdStrike', 'DATA'),
  stk('PANW', 'Palo Alto Nets', 'DATA'),
  stk('FTNT', 'Fortinet', 'DATA'),
  stk('ZS', 'Zscaler', 'DATA'),
  stk('OKTA', 'Okta', 'DATA'),
  stk('S', 'SentinelOne', 'DATA'),
  stk('TEAM', 'Atlassian', 'DATA'),
  stk('WDAY', 'Workday', 'DATA'),
  stk('AI', 'C3.ai', 'DATA'),
  stk('SMCI', 'Super Micro', 'DATA'),
  stk('ARM', 'Arm Holdings', 'DATA'),
  stk('COIN', 'Coinbase', 'DATA'),
  stk('TWLO', 'Twilio', 'DATA'),
  stk('ROKU', 'Roku', 'DATA'),
  stk('ZM',   'Zoom', 'DATA'),
  stk('PL',   'Planet Labs', 'DATA'),

  // AUTO / EV
  stk('TSLA', 'Tesla', 'AUTO'),
  stk('RIVN', 'Rivian', 'AUTO'),
  stk('LCID', 'Lucid', 'AUTO'),
  stk('NIO', 'NIO', 'AUTO'),
  stk('XPEV', 'XPeng', 'AUTO'),
  stk('LI', 'Li Auto', 'AUTO'),
  stk('F', 'Ford', 'AUTO'),
  stk('GM', 'General Motors', 'AUTO'),
  stk('STLA', 'Stellantis', 'AUTO'),

  // FINANCE / banks / cards / insurance
  stk('JPM', 'JPMorgan', 'FINANCE'),
  stk('BAC', 'Bank of America', 'FINANCE'),
  stk('GS', 'Goldman Sachs', 'FINANCE'),
  stk('WFC', 'Wells Fargo', 'FINANCE'),
  stk('C', 'Citigroup', 'FINANCE'),
  stk('MS', 'Morgan Stanley', 'FINANCE'),
  stk('SCHW', 'Charles Schwab', 'FINANCE'),
  stk('USB', 'US Bancorp', 'FINANCE'),
  stk('PNC', 'PNC Financial', 'FINANCE'),
  stk('TFC', 'Truist Financial', 'FINANCE'),
  stk('V', 'Visa', 'FINANCE'),
  stk('MA', 'Mastercard', 'FINANCE'),
  stk('AXP', 'American Express', 'FINANCE'),
  stk('BLK', 'BlackRock', 'FINANCE'),
  stk('PGR', 'Progressive', 'FINANCE'),
  stk('AIG', 'AIG', 'FINANCE'),
  stk('MET', 'MetLife', 'FINANCE'),
  stk('PRU', 'Prudential', 'FINANCE'),
  { ...stk('BRK-B', 'Berkshire Hathaway', 'FINANCE'), symbol: 'BRK.B' },

  // HEALTH / biotech / pharma
  stk('LLY', 'Eli Lilly', 'HEALTH'),
  stk('UNH', 'UnitedHealth', 'HEALTH'),
  stk('JNJ', 'Johnson & Johnson', 'HEALTH'),
  stk('PFE', 'Pfizer', 'HEALTH'),
  stk('MRNA', 'Moderna', 'HEALTH'),
  stk('BNTX', 'BioNTech', 'HEALTH'),
  stk('ABT', 'Abbott', 'HEALTH'),
  stk('ABBV', 'AbbVie', 'HEALTH'),
  stk('MRK', 'Merck', 'HEALTH'),
  stk('BMY', 'Bristol Myers', 'HEALTH'),
  stk('ELV', 'Elevance Health', 'HEALTH'),
  stk('CVS', 'CVS Health', 'HEALTH'),
  stk('CI', 'Cigna', 'HEALTH'),
  stk('HCA', 'HCA Healthcare', 'HEALTH'),
  stk('SYK', 'Stryker', 'HEALTH'),
  stk('MDT', 'Medtronic', 'HEALTH'),
  stk('ZTS', 'Zoetis', 'HEALTH'),
  stk('NVO', 'Novo Nordisk', 'HEALTH'),
  stk('AZN', 'AstraZeneca', 'HEALTH'),
  stk('NVS', 'Novartis', 'HEALTH'),
  stk('AMGN', 'Amgen', 'HEALTH'),
  stk('GILD', 'Gilead', 'HEALTH'),
  stk('VRTX', 'Vertex', 'HEALTH'),
  stk('REGN', 'Regeneron', 'HEALTH'),
  stk('ISRG', 'Intuitive Surgical', 'HEALTH'),
  stk('BIIB', 'Biogen', 'HEALTH'),

  // CONSUMER / retail / staples
  stk('WMT', 'Walmart', 'CONSUMER'),
  stk('COST', 'Costco', 'CONSUMER'),
  stk('HD', 'Home Depot', 'CONSUMER'),
  stk('LOW', "Lowe's", 'CONSUMER'),
  stk('TGT', 'Target', 'CONSUMER'),
  stk('DG',  'Dollar General', 'CONSUMER'),
  stk('DLTR','Dollar Tree', 'CONSUMER'),
  stk('ROST','Ross Stores', 'CONSUMER'),
  stk('TJX', 'TJX', 'CONSUMER'),
  stk('MCD', "McDonald's", 'CONSUMER'),
  stk('SBUX', 'Starbucks', 'CONSUMER'),
  stk('CMG', 'Chipotle', 'CONSUMER'),
  stk('YUM', 'Yum Brands', 'CONSUMER'),
  stk('KO', 'Coca-Cola', 'CONSUMER'),
  stk('PEP', 'PepsiCo', 'CONSUMER'),
  stk('PG', 'Procter & Gamble', 'CONSUMER'),
  stk('KMB','Kimberly-Clark','CONSUMER'),
  stk('EL', 'Estée Lauder', 'CONSUMER'),
  stk('NKE', 'Nike', 'CONSUMER'),
  stk('LULU', 'Lululemon', 'CONSUMER'),
  stk('DIS', 'Disney', 'CONSUMER'),
  stk('WBD', 'Warner Bros Discovery', 'CONSUMER'),
  stk('PARA','Paramount', 'CONSUMER'),
  stk('MO', 'Altria', 'CONSUMER'),
  stk('PM', 'Philip Morris', 'CONSUMER'),

  // OIL & GAS equities
  stk('XOM', 'ExxonMobil', 'OIL'),
  stk('CVX', 'Chevron', 'OIL'),
  stk('COP', 'ConocoPhillips', 'OIL'),
  stk('SLB', 'SLB', 'OIL'),
  stk('OXY', 'Occidental', 'OIL'),
  stk('MPC', 'Marathon Petroleum', 'OIL'),
  stk('PSX', 'Phillips 66', 'OIL'),
  stk('EOG', 'EOG Resources', 'OIL'),
  stk('VLO', 'Valero Energy', 'OIL'),
  stk('KMI', 'Kinder Morgan', 'OIL'),
  stk('WMB', 'Williams Cos', 'OIL'),
  stk('HAL', 'Halliburton', 'OIL'),

  // INDUSTRIALS / aerospace / defense
  stk('BA', 'Boeing', 'INDUST'),
  stk('CAT', 'Caterpillar', 'INDUST'),
  stk('GE', 'GE Aerospace', 'INDUST'),
  stk('HON', 'Honeywell', 'INDUST'),
  stk('RTX', 'RTX', 'INDUST'),
  stk('LMT', 'Lockheed Martin', 'INDUST'),
  stk('NOC', 'Northrop Grumman', 'INDUST'),
  stk('DE', 'Deere', 'INDUST'),
  stk('UPS', 'UPS', 'INDUST'),
  stk('FDX', 'FedEx', 'INDUST'),
  stk('RDW', 'Redwire', 'INDUST'),

  // TELECOM
  stk('T', 'AT&T', 'TELECOM'),
  stk('VZ', 'Verizon', 'TELECOM'),
  stk('TMUS', 'T-Mobile', 'TELECOM'),
  stk('CMCSA', 'Comcast', 'TELECOM'),

  // REIT
  stk('O', 'Realty Income', 'REIT'),
  stk('AMT', 'American Tower', 'REIT'),
  stk('PLD', 'Prologis', 'REIT'),
  stk('SPG', 'Simon Property', 'REIT'),
  stk('EQIX', 'Equinix', 'REIT'),

  // UTIL
  stk('NEE', 'NextEra Energy', 'UTIL'),
  stk('DUK', 'Duke Energy', 'UTIL'),
  stk('AEP', 'American Electric Power', 'UTIL'),
  stk('SO', 'Southern Co', 'UTIL'),

  // AIRLINES / TRAVEL
  stk('DAL', 'Delta Air Lines', 'TRAVEL'),
  stk('UAL', 'United Airlines', 'TRAVEL'),
  stk('LUV', 'Southwest Airlines', 'TRAVEL'),
  stk('AAL', 'American Airlines', 'TRAVEL'),
  stk('BKNG', 'Booking Holdings', 'TRAVEL'),
  stk('MAR', 'Marriott', 'TRAVEL'),
  stk('EXPE', 'Expedia', 'TRAVEL'),
  stk('CCL', 'Carnival', 'TRAVEL'),

  // ASIA / EMERGING
  stk('BABA', 'Alibaba', 'ASIA'),
  stk('JD', 'JD.com', 'ASIA'),
  stk('PDD', 'PDD Holdings', 'ASIA'),
  stk('BIDU', 'Baidu', 'ASIA'),
  stk('SE', 'Sea Ltd', 'ASIA'),
  stk('MELI', 'MercadoLibre', 'ASIA'),

  // MOMENTUM / popular speculative
  stk('HOOD', 'Robinhood', 'MOMENTUM'),
  stk('RBLX', 'Roblox', 'MOMENTUM'),
  stk('ABNB', 'Airbnb', 'MOMENTUM'),
  stk('SHOP', 'Shopify', 'MOMENTUM'),
  stk('SQ', 'Block', 'MOMENTUM'),
  stk('PYPL', 'PayPal', 'MOMENTUM'),
  stk('UBER', 'Uber', 'MOMENTUM'),
  stk('LYFT', 'Lyft', 'MOMENTUM'),
  stk('SPOT', 'Spotify', 'MOMENTUM'),
  stk('MSTR', 'MicroStrategy', 'MOMENTUM'),
  stk('RIOT', 'Riot Platforms', 'MOMENTUM'),
  stk('MARA', 'Marathon Digital', 'MOMENTUM'),
  stk('DKNG', 'DraftKings', 'MOMENTUM'),
  stk('SOFI', 'SoFi', 'MOMENTUM'),
  stk('GME', 'GameStop', 'MOMENTUM'),
  stk('AMC', 'AMC Entertainment', 'MOMENTUM'),
  stk('CBRS', 'CBRS', 'MOMENTUM'),
  stk('WAR',  'WAR', 'MOMENTUM'),

  // CRYPTO
  crypto('BTC', 'Bitcoin'),
  crypto('ETH', 'Ethereum'),
  crypto('SOL', 'Solana'),
  crypto('BNB', 'BNB'),
  crypto('XRP', 'Ripple'),
  crypto('DOGE', 'Dogecoin'),
  crypto('ADA', 'Cardano'),
  crypto('AVAX', 'Avalanche'),
  crypto('DOT', 'Polkadot'),
  crypto('LINK', 'Chainlink'),
  crypto('MATIC', 'Polygon'),
  crypto('ATOM', 'Cosmos'),
  crypto('NEAR', 'Near'),
  crypto('APT', 'Aptos'),
  crypto('LTC', 'Litecoin'),
  crypto('TRX', 'Tron'),

  // MACRO
  idx('SPX', 'SPX', 'S&P 500', 'index', '^GSPC'),
  idx('NDX', 'NDX', 'Nasdaq Composite', 'index', '^IXIC'),
  idx('DJI', 'DJI', 'Dow Jones', 'index', '^DJI'),
  idx('VIX', 'VIX', 'VIX', 'index', '^VIX'),
  idx('TNX', 'US10Y', 'US 10Y Yield', '%', '^TNX'),
  idx('DXY', 'DXY', 'Dollar Index', 'index', 'DX=F'),

  // FX — used by the converter and by the dashboard currency switcher.
  // Not displayed as a list on any tab.
  fx('EUR', 'USD', 'Euro / US Dollar'),
  fx('GBP', 'USD', 'Pound / US Dollar'),
  fx('AUD', 'USD', 'Australian Dollar / US Dollar'),
  fx('NZD', 'USD', 'NZ Dollar / US Dollar'),
  fx('USD', 'JPY', 'US Dollar / Japanese Yen'),
  fx('USD', 'CHF', 'US Dollar / Swiss Franc'),
  fx('USD', 'CAD', 'US Dollar / Canadian Dollar'),
  fx('USD', 'CNY', 'US Dollar / Chinese Yuan'),
  fx('USD', 'INR', 'US Dollar / Indian Rupee'),
  fx('USD', 'MXN', 'US Dollar / Mexican Peso'),
  fx('USD', 'BRL', 'US Dollar / Brazilian Real'),
  fx('USD', 'KRW', 'US Dollar / Korean Won'),
  fx('USD', 'SGD', 'US Dollar / Singapore Dollar'),
  fx('USD', 'HKD', 'US Dollar / Hong Kong Dollar'),
  fx('USD', 'TWD', 'US Dollar / Taiwan Dollar'),
  fx('USD', 'THB', 'US Dollar / Thai Baht'),
  fx('USD', 'IDR', 'US Dollar / Indonesian Rupiah'),
  fx('USD', 'PHP', 'US Dollar / Philippine Peso'),
  fx('USD', 'MYR', 'US Dollar / Malaysian Ringgit'),
  fx('USD', 'VND', 'US Dollar / Vietnamese Dong'),
  fx('USD', 'AED', 'US Dollar / UAE Dirham'),
  fx('USD', 'SAR', 'US Dollar / Saudi Riyal'),
  fx('USD', 'ILS', 'US Dollar / Israeli Shekel'),
  fx('USD', 'TRY', 'US Dollar / Turkish Lira'),
  fx('USD', 'ZAR', 'US Dollar / South African Rand'),
  fx('USD', 'EGP', 'US Dollar / Egyptian Pound'),
  fx('USD', 'NGN', 'US Dollar / Nigerian Naira'),
  fx('USD', 'KES', 'US Dollar / Kenyan Shilling'),
  fx('USD', 'PKR', 'US Dollar / Pakistani Rupee'),
  fx('USD', 'BDT', 'US Dollar / Bangladeshi Taka'),
  fx('USD', 'SEK', 'US Dollar / Swedish Krona'),
  fx('USD', 'NOK', 'US Dollar / Norwegian Krone'),
  fx('USD', 'DKK', 'US Dollar / Danish Krone'),
  fx('USD', 'PLN', 'US Dollar / Polish Zloty'),
  fx('USD', 'CZK', 'US Dollar / Czech Koruna'),
  fx('USD', 'HUF', 'US Dollar / Hungarian Forint'),
  fx('USD', 'RON', 'US Dollar / Romanian Leu'),
  fx('USD', 'ARS', 'US Dollar / Argentine Peso'),
  fx('USD', 'CLP', 'US Dollar / Chilean Peso'),
  fx('USD', 'COP', 'US Dollar / Colombian Peso'),
  fx('USD', 'PEN', 'US Dollar / Peruvian Sol'),
];

export const ALLOWED_RANGES = {
  '1d':  { range: '1d',  interval: '5m'  },
  '5d':  { range: '5d',  interval: '30m' },
  '1mo': { range: '1mo', interval: '1d'  },
  '3mo': { range: '3mo', interval: '1d'  },
  '6mo': { range: '6mo', interval: '1d'  },
  '1y':  { range: '1y',  interval: '1wk' },
  'ytd': { range: 'ytd', interval: '1d'  },
};

export const findSymbol = (ticker) =>
  SYMBOLS.find((s) => s.ticker.toUpperCase() === String(ticker || '').toUpperCase());

// Currency display metadata used by both the converter and the
// dashboard ccy switcher.
export const CURRENCY_META = {
  USD: { sym: '$',     name: 'US Dollar' },
  EUR: { sym: '€',     name: 'Euro' },
  GBP: { sym: '£',     name: 'British Pound' },
  JPY: { sym: '¥',     name: 'Japanese Yen' },
  CHF: { sym: 'CHF ',  name: 'Swiss Franc' },
  CAD: { sym: 'C$',    name: 'Canadian Dollar' },
  AUD: { sym: 'A$',    name: 'Australian Dollar' },
  NZD: { sym: 'NZ$',   name: 'New Zealand Dollar' },
  CNY: { sym: '¥',     name: 'Chinese Yuan' },
  INR: { sym: '₹',     name: 'Indian Rupee' },
  MXN: { sym: 'MX$',   name: 'Mexican Peso' },
  BRL: { sym: 'R$',    name: 'Brazilian Real' },
  KRW: { sym: '₩',     name: 'Korean Won' },
  SGD: { sym: 'S$',    name: 'Singapore Dollar' },
  HKD: { sym: 'HK$',   name: 'Hong Kong Dollar' },
  TWD: { sym: 'NT$',   name: 'Taiwan Dollar' },
  THB: { sym: '฿',     name: 'Thai Baht' },
  IDR: { sym: 'Rp',    name: 'Indonesian Rupiah' },
  PHP: { sym: '₱',     name: 'Philippine Peso' },
  MYR: { sym: 'RM',    name: 'Malaysian Ringgit' },
  VND: { sym: '₫',     name: 'Vietnamese Dong' },
  AED: { sym: 'AED ',  name: 'UAE Dirham' },
  SAR: { sym: 'SAR ',  name: 'Saudi Riyal' },
  ILS: { sym: '₪',     name: 'Israeli Shekel' },
  TRY: { sym: '₺',     name: 'Turkish Lira' },
  ZAR: { sym: 'R',     name: 'South African Rand' },
  EGP: { sym: 'E£',    name: 'Egyptian Pound' },
  NGN: { sym: '₦',     name: 'Nigerian Naira' },
  KES: { sym: 'KSh',   name: 'Kenyan Shilling' },
  PKR: { sym: '₨',     name: 'Pakistani Rupee' },
  BDT: { sym: '৳',     name: 'Bangladeshi Taka' },
  SEK: { sym: 'kr',    name: 'Swedish Krona' },
  NOK: { sym: 'kr',    name: 'Norwegian Krone' },
  DKK: { sym: 'kr',    name: 'Danish Krone' },
  PLN: { sym: 'zł',    name: 'Polish Zloty' },
  CZK: { sym: 'Kč',    name: 'Czech Koruna' },
  HUF: { sym: 'Ft',    name: 'Hungarian Forint' },
  RON: { sym: 'lei',   name: 'Romanian Leu' },
  ARS: { sym: 'AR$',   name: 'Argentine Peso' },
  CLP: { sym: 'CL$',   name: 'Chilean Peso' },
  COP: { sym: 'CO$',   name: 'Colombian Peso' },
  PEN: { sym: 'S/',    name: 'Peruvian Sol' },
};

export const CURRENCY_NO_DECIMAL = new Set(['JPY', 'KRW', 'IDR', 'VND', 'CLP', 'HUF', 'TWD', 'COP']);
