import React, { useEffect, useState } from 'react';

const tierClass = (tier) => ({
  positive: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40',
  negative: 'bg-red-500/15 text-red-300 border-red-500/40',
  caution:  'bg-orange-500/15 text-orange-300 border-orange-500/40',
  mixed:    'bg-yellow-500/15 text-yellow-300 border-yellow-500/40',
  neutral:  'bg-gray-500/15 text-gray-300 border-gray-700',
}[tier] || 'bg-gray-500/15 text-gray-300 border-gray-700');

const Section = ({ label, body }) => {
  if (!body) return null;
  return (
    <div>
      <div className="text-[10px] uppercase tracking-widest text-cyan-300/80 mb-1">{label}</div>
      <p className="text-xs sm:text-[13px] text-gray-200 leading-relaxed">{body}</p>
    </div>
  );
};

export default function AnalysisPanel({ asset }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState(null);
  const [bumper, setBumper] = useState(0);

  useEffect(() => {
    if (!asset) return;
    let cancelled = false;
    setLoading(true);
    setErr(null);
    fetch(`/api/analysis?ticker=${encodeURIComponent(asset.ticker)}${bumper ? `&_=${bumper}` : ''}`)
      .then((r) => r.ok ? r.json() : Promise.reject(new Error(`status ${r.status}`)))
      .then((j) => {
        if (cancelled) return;
        if (!j.ok) throw new Error(j.error || 'failed');
        setData(j);
        setLoading(false);
      })
      .catch((e) => {
        if (cancelled) return;
        setErr(String(e?.message || e));
        setLoading(false);
      });
    return () => { cancelled = true; };
  }, [asset?.ticker, bumper]);

  return (
    <div className="rounded-xl border border-cyan-700/30 bg-gradient-to-br from-gray-900/95 to-gray-900/60 p-4 sm:p-5 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-gradient-to-br from-cyan-400 to-violet-500 grid place-items-center shadow-glow">
            <span className="text-[10px] font-bold text-gray-950">AI</span>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-widest text-gray-500">AI Analysis</div>
            <div className="text-sm font-semibold text-gray-100">{asset?.name || ''} <span className="text-gray-500 font-mono">· {asset?.ticker || ''}</span></div>
          </div>
        </div>
        <button
          onClick={() => setBumper(Date.now())}
          disabled={loading}
          className="text-[10px] uppercase tracking-widest px-2.5 py-1 rounded-md border border-gray-800 bg-gray-900 text-gray-300 hover:border-gray-600 hover:text-white disabled:opacity-50"
        >
          {loading ? 'analysing…' : 'refresh'}
        </button>
      </div>

      {err && (
        <div className="text-xs text-red-300 border border-red-500/30 bg-red-500/10 rounded p-2">
          Failed to load analysis: {err}
        </div>
      )}

      {/* Technical signals — always available */}
      {data?.signals?.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {data.signals.map((s, i) => (
            <span key={i} className={`text-[10px] uppercase tracking-wider px-2 py-1 rounded-md border ${tierClass(s.tier)}`}>
              {s.text}
            </span>
          ))}
        </div>
      )}

      {/* Key technicals strip */}
      {data?.technicals && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
          <Stat label="1m return"  val={data.technicals.return_1m  != null ? `${data.technicals.return_1m  >= 0 ? '+' : ''}${data.technicals.return_1m.toFixed(1)}%`  : '—'} />
          <Stat label="3m return"  val={data.technicals.return_3m  != null ? `${data.technicals.return_3m  >= 0 ? '+' : ''}${data.technicals.return_3m.toFixed(1)}%`  : '—'} />
          <Stat label="RSI(14)"    val={data.technicals.rsi14      != null ? data.technicals.rsi14.toFixed(0) : '—'} />
          <Stat label="Volatility" val={`${data.technicals.vol_annual.toFixed(0)}%`} />
        </div>
      )}

      {/* AI narrative */}
      {data?.ai && (
        <div className="space-y-3 pt-2 border-t border-gray-800">
          <Section label="Trend"     body={data.ai.trend} />
          <Section label="Catalysts" body={data.ai.catalysts} />
          <Section label="Risks"     body={data.ai.risks} />
          <Section label="Outlook"   body={data.ai.outlook} />
          <div className="text-[9px] uppercase tracking-widest text-gray-600 pt-1">
            Generated by {data.ai.model}
          </div>
        </div>
      )}

      {/* AI unavailable notice */}
      {data && !data.aiAvailable && (
        <div className="text-[11px] text-gray-500 border border-gray-800 bg-gray-950/50 rounded-md p-3 space-y-1">
          <div className="text-amber-400 uppercase tracking-widest text-[10px]">AI narrative disabled</div>
          <div>
            Get a free key at <a href="https://console.groq.com" target="_blank" rel="noopener noreferrer"
              className="text-cyan-300 underline">console.groq.com</a> and set{' '}
            <code className="font-mono text-cyan-300">GROQ_API_KEY</code> in your Vercel project's environment
            variables (Settings → Environment Variables). The technical signals above work without it.
          </div>
        </div>
      )}

      {/* AI error fallback */}
      {data?.aiAvailable && data?.aiError && !data.ai && (
        <div className="text-[11px] text-amber-300 border border-amber-700/40 bg-amber-500/5 rounded-md p-2">
          AI narrative failed: <span className="font-mono">{data.aiError}</span>
        </div>
      )}

      {!loading && !err && !data && (
        <div className="text-xs text-gray-500">No analysis yet.</div>
      )}

      {loading && !data && (
        <div className="space-y-2">
          {[0, 1, 2].map((i) => (
            <div key={i} className="h-3 rounded bg-gray-800/70 animate-pulse" style={{ width: `${90 - i * 10}%` }} />
          ))}
        </div>
      )}
    </div>
  );
}

const Stat = ({ label, val }) => (
  <div className="bg-gray-950/40 border border-gray-800 rounded-md px-3 py-2">
    <div className="text-[10px] uppercase tracking-widest text-gray-500">{label}</div>
    <div className="font-mono text-xs text-gray-100 mt-0.5">{val}</div>
  </div>
);
