import React, { useEffect, useId, useState } from 'react';
import { readDashboardJson } from '../lib/apiClient.js';

export default function Briefing() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState(null);
  const [open, setOpen] = useState(true);
  const [requestVersion, setRequestVersion] = useState(0);
  const detailsId = useId();

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setErr(null);
    fetch('/api/briefing')
      .then(readDashboardJson)
      .then((j) => {
        if (cancelled) return;
        setData(j);
        setLoading(false);
      })
      .catch((e) => {
        if (cancelled) return;
        setErr(String(e?.message || e));
        setLoading(false);
      });
    return () => { cancelled = true; };
  }, [requestVersion]);

  const aiMessage = data?.aiError || data?.error?.message || data?.aiStatus?.message;

  return (
    <div className="rounded-xl border border-cyan-700/30 bg-gradient-to-br from-cyan-900/20 via-gray-900/80 to-gray-900/40 overflow-hidden">
      <div className="w-full flex items-center hover:bg-white/5 transition-colors">
        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
          aria-controls={detailsId}
          aria-label={`${open ? 'Collapse' : 'Expand'} market briefing`}
          className="min-w-0 flex-1 flex items-center justify-between gap-3 pl-4 sm:pl-5 pr-2 py-3 text-left"
        >
          <div className="flex items-center gap-2 min-w-0">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-cyan-400 to-violet-500 grid place-items-center shadow-glow shrink-0">
              <span className="text-[10px] font-bold text-gray-950">AI</span>
            </div>
            <div className="min-w-0">
              <div className="text-[10px] uppercase tracking-widest text-cyan-300/80">Market Briefing</div>
              <div className="text-sm text-gray-100 truncate">
                {loading ? 'Generating today\'s briefing…' : (data?.briefing ? 'Today\'s market in three paragraphs' : 'Briefing')}
              </div>
            </div>
          </div>
          <span aria-hidden="true" className="text-gray-500 text-base shrink-0">{open ? '▾' : '▸'}</span>
        </button>
        <button
          type="button"
          onClick={() => setRequestVersion((version) => version + 1)}
          disabled={loading}
          aria-label="Refresh market briefing"
          className="mr-4 sm:mr-5 shrink-0 text-[10px] uppercase tracking-widest px-2.5 py-1 rounded-md border border-gray-800 bg-gray-900 text-gray-300 hover:border-gray-600 hover:text-white disabled:opacity-50"
        >{loading ? '…' : 'refresh'}</button>
      </div>

      {open && (
        <div id={detailsId} role="region" aria-label="Market briefing details" className="border-t border-gray-800 p-4 sm:p-5 space-y-3">
          {err && <div role="alert" className="text-xs text-red-300">Failed: {err}</div>}

          {data?.briefing?.text && (
            <div className="text-xs sm:text-sm text-gray-200 leading-relaxed whitespace-pre-line">
              {data.briefing.text}
            </div>
          )}

          {data && !data.briefing && data.aiAvailable && (
            <div role="status" aria-live="polite" className="text-xs text-amber-300">
              AI briefing unavailable: {aiMessage || 'Please try again shortly.'}
            </div>
          )}

          {data && !data.aiAvailable && (
            <div className="text-[11px] text-gray-500 border border-gray-800 bg-gray-950/50 rounded-md p-3">
              <span className="text-amber-400 uppercase tracking-widest text-[10px]">AI briefing disabled</span>
              <span> — set <code className="font-mono text-cyan-300">GROQ_API_KEY</code> in Vercel env vars to enable.</span>
            </div>
          )}

          {/* Mini-snapshot of signals as fallback context */}
          {data?.signals && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2 border-t border-gray-800">
              <SignalList title="Top Gainers" rows={data.signals.gainers} positive />
              <SignalList title="Top Losers"  rows={data.signals.losers}  positive={false} />
            </div>
          )}

          {data?.briefing && (
            <div className="text-[9px] uppercase tracking-widest text-gray-600 pt-1">
              Generated by {data.briefing.model} · {new Date(data.generatedAt).toUTCString().slice(17, 25)}Z
            </div>
          )}

          {loading && !data && (
            <div role="status" aria-live="polite" aria-label="Loading market briefing" className="space-y-2">
              {[0, 1, 2].map((i) => (
                <div key={i} className="h-3 rounded bg-gray-800/70 animate-pulse" style={{ width: `${95 - i * 5}%` }} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

const SignalList = ({ title, rows, positive }) => (
  <div>
    <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">{title}</div>
    <ul className="space-y-1">
      {(rows || []).slice(0, 3).map((r) => (
        <li key={r.ticker} className="flex items-center gap-2 text-xs">
          <span className="font-mono text-gray-100 w-14">{r.ticker}</span>
          <span className="text-gray-400 truncate flex-1">{r.name}</span>
          <span className={`font-mono ${positive ? 'text-emerald-400' : 'text-red-400'}`}>
            {r.changePct >= 0 ? '+' : ''}{r.changePct.toFixed(2)}%
          </span>
        </li>
      ))}
    </ul>
  </div>
);
